-- Rehearse — question bank seed data (12 questions per role)

insert into
  public.questions (role, difficulty, category, text)
values
  -- ── software-engineer ────────────────────────────────────────────────
  ('software-engineer', 'easy', 'behavioral', 'Tell me about yourself and your journey into software engineering.'),
  ('software-engineer', 'medium', 'behavioral', 'Describe a time you disagreed with a teammate about a technical decision. How did you resolve it?'),
  ('software-engineer', 'medium', 'behavioral', 'Tell me about a project you''re most proud of and what made it successful.'),
  ('software-engineer', 'hard', 'behavioral', 'Describe a time you had to deliver bad news about a missed deadline. How did you handle it?'),
  ('software-engineer', 'easy', 'technical', 'Walk me through how you would debug a function that''s returning incorrect results.'),
  ('software-engineer', 'medium', 'technical', 'How would you design a URL shortening service?'),
  ('software-engineer', 'medium', 'technical', 'Explain the tradeoffs between SQL and NoSQL databases for a given use case.'),
  ('software-engineer', 'hard', 'technical', 'How would you scale a system currently handling 1,000 requests per second to handle 100,000?'),
  ('software-engineer', 'easy', 'situational', 'You just noticed a bug in production right before a release. What do you do?'),
  ('software-engineer', 'medium', 'situational', 'Your team is behind schedule on a sprint. How do you prioritize the remaining work?'),
  ('software-engineer', 'medium', 'situational', 'A teammate keeps submitting code without tests. How do you address this?'),
  ('software-engineer', 'hard', 'situational', 'You inherit a legacy codebase with no documentation and a tight deadline. How do you approach it?'),

  -- ── frontend ──────────────────────────────────────────────────────────
  ('frontend', 'easy', 'behavioral', 'Tell me about a UI you built that you''re particularly proud of.'),
  ('frontend', 'medium', 'behavioral', 'Describe a time you had to push back on a design that wasn''t technically feasible.'),
  ('frontend', 'medium', 'behavioral', 'Tell me about a time you improved the performance of a web application.'),
  ('frontend', 'hard', 'behavioral', 'Describe a conflict with a designer or product manager over UX priorities and how you resolved it.'),
  ('frontend', 'easy', 'technical', 'What''s the difference between let, const, and var in JavaScript?'),
  ('frontend', 'medium', 'technical', 'How would you optimize a React app that''s re-rendering too often?'),
  ('frontend', 'medium', 'technical', 'Explain how the browser''s critical rendering path works.'),
  ('frontend', 'hard', 'technical', 'How would you architect a design system to be used across multiple product teams?'),
  ('frontend', 'easy', 'situational', 'A stakeholder wants a pixel-perfect implementation that doesn''t work responsively. What do you do?'),
  ('frontend', 'medium', 'situational', 'You discover a memory leak in production. How do you diagnose and fix it?'),
  ('frontend', 'medium', 'situational', 'Your team wants to adopt a new frontend framework. How do you evaluate whether it''s worth the migration?'),
  ('frontend', 'hard', 'situational', 'You need to support a product on very old browsers while keeping modern code clean. How do you handle it?'),

  -- ── backend ───────────────────────────────────────────────────────────
  ('backend', 'easy', 'behavioral', 'Tell me about a backend system you designed from scratch.'),
  ('backend', 'medium', 'behavioral', 'Describe a time a service you owned went down. What did you do?'),
  ('backend', 'medium', 'behavioral', 'Tell me about a time you improved an API''s reliability or performance.'),
  ('backend', 'hard', 'behavioral', 'Describe a disagreement with another team about an API contract and how it was resolved.'),
  ('backend', 'easy', 'technical', 'What''s the difference between REST and GraphQL?'),
  ('backend', 'medium', 'technical', 'How would you design a rate limiter for a public API?'),
  ('backend', 'medium', 'technical', 'Explain how you''d handle database migrations with zero downtime.'),
  ('backend', 'hard', 'technical', 'How would you design a distributed job queue that guarantees at-least-once delivery?'),
  ('backend', 'easy', 'situational', 'You notice a query is timing out intermittently in production. What''s your first step?'),
  ('backend', 'medium', 'situational', 'Your service''s error rate spikes after a deploy. Walk me through your response.'),
  ('backend', 'medium', 'situational', 'Two microservices are tightly coupled and causing cascading failures. How would you address it?'),
  ('backend', 'hard', 'situational', 'You need to migrate a critical service to a new database with no downtime. How do you plan it?'),

  -- ── data-scientist ────────────────────────────────────────────────────
  ('data-scientist', 'easy', 'behavioral', 'Tell me about a data project where your analysis changed a business decision.'),
  ('data-scientist', 'medium', 'behavioral', 'Describe a time your analysis was wrong. How did you find out, and what did you do?'),
  ('data-scientist', 'medium', 'behavioral', 'Tell me about a time you had to explain a complex model to a non-technical stakeholder.'),
  ('data-scientist', 'hard', 'behavioral', 'Describe a time you disagreed with a product decision based on data you had.'),
  ('data-scientist', 'easy', 'technical', 'How do you handle missing data in a dataset?'),
  ('data-scientist', 'medium', 'technical', 'Explain the bias-variance tradeoff.'),
  ('data-scientist', 'medium', 'technical', 'How would you design an A/B test for a new feature?'),
  ('data-scientist', 'hard', 'technical', 'How would you detect and handle data drift in a production model?'),
  ('data-scientist', 'easy', 'situational', 'Stakeholders want a definitive answer but your data is inconclusive. What do you do?'),
  ('data-scientist', 'medium', 'situational', 'You find that a dataset used for a live model has quality issues. How do you respond?'),
  ('data-scientist', 'medium', 'situational', 'Your analysis contradicts what leadership expects to hear. How do you present it?'),
  ('data-scientist', 'hard', 'situational', 'A model performs well in testing but poorly in production. How do you investigate?'),

  -- ── ml-engineer ───────────────────────────────────────────────────────
  ('ml-engineer', 'easy', 'behavioral', 'Tell me about an ML model you took from prototype to production.'),
  ('ml-engineer', 'medium', 'behavioral', 'Describe a time a model you deployed underperformed. What did you do?'),
  ('ml-engineer', 'medium', 'behavioral', 'Tell me about a time you had to balance model accuracy against latency or cost constraints.'),
  ('ml-engineer', 'hard', 'behavioral', 'Describe a disagreement with a data scientist about a modeling approach and how it was resolved.'),
  ('ml-engineer', 'easy', 'technical', 'What''s the difference between batch and online inference?'),
  ('ml-engineer', 'medium', 'technical', 'How would you design a feature store for a team with multiple ML models?'),
  ('ml-engineer', 'medium', 'technical', 'Explain how you''d monitor a model in production for degradation.'),
  ('ml-engineer', 'hard', 'technical', 'How would you design a system for retraining models automatically as new data arrives?'),
  ('ml-engineer', 'easy', 'situational', 'A model''s predictions suddenly look wrong in production. What''s your first step?'),
  ('ml-engineer', 'medium', 'situational', 'You need to ship a model under a tight deadline with imperfect data. How do you proceed?'),
  ('ml-engineer', 'medium', 'situational', 'Your training pipeline is slow and blocking iteration. How do you speed it up?'),
  ('ml-engineer', 'hard', 'situational', 'You discover your production model has a fairness or bias issue. How do you handle it?'),

  -- ── product-manager ───────────────────────────────────────────────────
  ('product-manager', 'easy', 'behavioral', 'Tell me about a product you shipped that you''re proud of.'),
  ('product-manager', 'medium', 'behavioral', 'Describe a time you had to say no to a stakeholder''s feature request.'),
  ('product-manager', 'medium', 'behavioral', 'Tell me about a time you used data to change the direction of a product.'),
  ('product-manager', 'hard', 'behavioral', 'Describe a time a launch failed. What happened and what did you learn?'),
  ('product-manager', 'easy', 'technical', 'How do you prioritize a backlog with limited engineering resources?'),
  ('product-manager', 'medium', 'technical', 'Walk me through how you''d define success metrics for a new feature.'),
  ('product-manager', 'medium', 'technical', 'How would you approach writing a PRD for a feature with ambiguous requirements?'),
  ('product-manager', 'hard', 'technical', 'How would you decide whether to build, buy, or partner for a new capability?'),
  ('product-manager', 'easy', 'situational', 'Engineering says a requested feature will take twice as long as planned. What do you do?'),
  ('product-manager', 'medium', 'situational', 'Two important stakeholders want conflicting priorities for the next sprint. How do you resolve it?'),
  ('product-manager', 'medium', 'situational', 'User feedback and internal data are pointing in opposite directions. How do you decide?'),
  ('product-manager', 'hard', 'situational', 'A competitor just launched a feature your roadmap had planned for next quarter. How do you respond?'),

  -- ── ui-ux-designer ────────────────────────────────────────────────────
  ('ui-ux-designer', 'easy', 'behavioral', 'Walk me through a design project from research to final product.'),
  ('ui-ux-designer', 'medium', 'behavioral', 'Describe a time user research changed your design significantly.'),
  ('ui-ux-designer', 'medium', 'behavioral', 'Tell me about a time you had to defend a design decision to engineering or leadership.'),
  ('ui-ux-designer', 'hard', 'behavioral', 'Describe a time you received harsh critique on your work. How did you respond?'),
  ('ui-ux-designer', 'easy', 'technical', 'How do you approach designing for accessibility?'),
  ('ui-ux-designer', 'medium', 'technical', 'Walk me through your process for conducting a usability test.'),
  ('ui-ux-designer', 'medium', 'technical', 'How would you design an onboarding flow for a complex B2B product?'),
  ('ui-ux-designer', 'hard', 'technical', 'How would you build and scale a design system across multiple product teams?'),
  ('ui-ux-designer', 'easy', 'situational', 'A stakeholder wants to skip user research to hit a deadline. What do you do?'),
  ('ui-ux-designer', 'medium', 'situational', 'Your usability testing reveals users don''t understand a core feature. How do you respond?'),
  ('ui-ux-designer', 'medium', 'situational', 'Engineering says your design isn''t technically feasible on the deadline. How do you handle it?'),
  ('ui-ux-designer', 'hard', 'situational', 'You''re asked to redesign a product with data showing conflicting user needs across segments. How do you proceed?'),

  -- ── hr-general ────────────────────────────────────────────────────────
  ('hr-general', 'easy', 'behavioral', 'Tell me about yourself.'),
  ('hr-general', 'easy', 'behavioral', 'Why are you interested in this role?'),
  ('hr-general', 'medium', 'behavioral', 'Tell me about a time you worked with a difficult team member.'),
  ('hr-general', 'medium', 'behavioral', 'Describe a time you failed at something. What did you learn?'),
  ('hr-general', 'medium', 'behavioral', 'Tell me about a time you had to manage multiple priorities under pressure.'),
  ('hr-general', 'hard', 'behavioral', 'Describe a time you received difficult feedback. How did you respond?'),
  ('hr-general', 'hard', 'behavioral', 'Tell me about a time you made a mistake that affected others. How did you handle it?'),
  ('hr-general', 'easy', 'situational', 'Where do you see yourself in five years?'),
  ('hr-general', 'easy', 'situational', 'What''s your greatest strength, and how has it helped you at work?'),
  ('hr-general', 'medium', 'situational', 'What''s your greatest weakness, and what are you doing about it?'),
  ('hr-general', 'medium', 'situational', 'How do you handle disagreements with your manager?'),
  ('hr-general', 'hard', 'situational', 'Why should we hire you over other candidates?');
